{
 "title": "Story Dashboard Aeneid by Cumulo",
 "description": "This dashboard provides a comprehensive overview of the health and performance of a Story Aeneid node. It monitors sync status, consensus metrics, block processing times, transaction activity, validator participation, and system resource usage. The dashboard helps identify network issues, node performance bottlenecks, and memory management efficiency, offering critical insights for maintaining an optimized and healthy node.\nFor detailed documentation of the metrics, visit:\nStory Node Metrics Documentation\nhttps://github.com/Cumulo-pro/Story_protocol/blob/main/monitoring/story_aeneid_metrics.md",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "job", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Panel Title",
   "type": "text",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 1 },
   "options": {
    "content": "<div style=\"text-align: center;\">\n    <img src=\"https://cumulo.pro/images/story.png\" alt=\"Logo\" style=\"height: 150px;\"> <!-- Ajusta la altura según sea necesario -->\n    <h2>Story Aeneid Node metrics</h2>\n    <h5>by <a href=\"https://cumulo.pro\">Cumulo</a></h5>\n    <p><a href=\"https://github.com/Cumulo-pro/Story_protocol/blob/main/monitoring/story_aeneid_metrics.md\">Story Node Metrics Documentation</a>\n</div>"
   }
  },
  {
   "title": "Sync Status ",
   "type": "stat",
   "description": "Indicates whether the node is synchronising blocks. Displays 1 if the node is synchronising and 0 if it is not, helping to diagnose the synchronisation status.",
   "gridPos": { "h": 8, "w": 4, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_blocksync_syncing{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consensus Height",
   "type": "stat",
   "description": "Number representing the last block reached by the node consensus.",
   "gridPos": { "h": 8, "w": 6, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_height{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Peers",
   "type": "gauge",
   "description": "This metric tracks the current number of peers that are connected to the node. A higher number of peers can indicate good network connectivity, ensuring a healthy and distributed exchange of information. However, monitoring the number of peers is essential to detect if there are too few (which might signal network partition or connectivity issues) or too many (which could lead to resource strain on the node). Maintaining an optimal number of peers ensures efficient block propagation, consensus participation, and overall network performance.",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_p2p_peers{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Validator Power",
   "type": "stat",
   "description": "Reports the voting power of each validator.",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_validator_power{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Chain Size ",
   "type": "stat",
   "description": "This metric shows the cumulative size of the blockchain as it grows over time, accounting for all blocks, transactions, and state data. ",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_chain_size_bytes{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nº Missing Validators",
   "type": "barchart",
   "description": "This metric shows the voting power (stake) that absent validators represent. A high power of absent validators can have a negative impact on the security and decentralization of the network, as it reduces the available consensus power. Value: total power of the validators who are absent in the consensus process.",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 9 },
   "targets": [
    {
     "expr": "cometbft_consensus_missing_validators{job=\"$job\"}",
     "legendFormat": "Nº validators"
    }
   ]
  },
  {
   "title": "Block Size",
   "type": "stat",
   "description": "Indicates the amount of data contained in the last block, in bytes.",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_block_size_bytes{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latest Block Height",
   "type": "stat",
   "description": "This is the number of the highest block processed by the node, indicating whether it is up to date with the network.",
   "gridPos": { "h": 7, "w": 7, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_latest_block_height{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Block Processing Time",
   "type": "timeseries",
   "description": "This metric provides the average time it takes for the node to process a block, calculated by dividing the total block processing time (cometbft_state_block_processing_time_sum) by the total number of blocks processed (cometbft_state_block_processing_time_count). Monitoring the average block processing time is crucial for evaluating the efficiency of block finalization. If the average time increases, it may indicate potential performance bottlenecks or issues with the node's processing power. Keeping the average block processing time within an optimal range helps ensure the smooth functioning of the network and avoids delays in transaction finalization.",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "cometbft_state_block_processing_time_sum{job=\"$job\"}",
     "legendFormat": "Block Processing Time Sum "
    },
    {
     "expr": "cometbft_state_block_processing_time_count{job=\"$job\"}",
     "legendFormat": "Block Processing Time Count"
    },
    { "expression": "$A/$B", "type": "math" }
   ]
  },
  {
   "title": "State Block  Processing Time",
   "type": "histogram",
   "description": "Measures block processing time. Records the time the node takes to process a block, which helps to evaluate its efficiency.\nThese metrics are fundamental for monitoring and diagnosing the performance and status of the node in the network.",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "cometbft_state_block_processing_time_bucket{job=\"$job\"}",
     "legendFormat": "le: {{le}}"
    }
   ]
  },
  {
   "title": "Proposal Receive Count",
   "type": "timeseries",
   "description": "This metric measures the total count of block proposals that the node has received over time. The proposals are annotated with their status, indicating whether they were accepted or rejected by the consensus process. Monitoring this helps in understanding the node's participation in the consensus mechanism and provides insights into the efficiency and reliability of the proposal process within the network. It is particularly useful for diagnosing any issues with block proposal acceptance rates.",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "cometbft_consensus_proposal_receive_count{job=\"$job\"}",
     "legendFormat": "Status: {{status}}"
    }
   ]
  },
  {
   "title": "Begin Blocker Duration",
   "type": "barchart",
   "description": "This metric measures the time taken to execute the begin blocker for various modules (e.g., distribution, mint, slashing, staking, upgrade). Begin blockers are executed at the start of each block to update the blockchain state and apply necessary logic before transactions are processed. The metric provides different quantiles (0.5, 0.9, 0.99) to show the distribution of execution times for each module. Monitoring this metric helps assess the performance of each module and identify potential bottlenecks that may impact the speed of block processing.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "cosmos_begin_blocker{job=\"$job\"}",
     "legendFormat": "quantile: {{quantile}}"
    }
   ]
  },
  {
   "title": "End Blocker Duration",
   "type": "timeseries",
   "description": "This metric measures the time taken to execute the end blocker for different modules (e.g., evmstaking, gov, staking) within the Cosmos SDK. End blockers are critical functions that are run at the end of each block in the blockchain to finalize state changes and apply governance, staking, and other processes. The metric uses different quantiles (0.5, 0.9, 0.99) to show the distribution of execution times, providing insights into the efficiency of the end blockers. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "targets": [
    { "expr": "cosmos_end_blocker", "legendFormat": "quantile: {{quantile}}" }
   ]
  },
  {
   "title": "Late Votes",
   "type": "timeseries",
   "description": "This metric captures instances where the node receives votes that are considered \"late,\" meaning they belong to earlier stages of the consensus process. The presence of late votes can indicate network delays, synchronization issues, or potential inefficiencies in message propagation. Monitoring this helps in diagnosing network health and ensuring that nodes are maintaining timely consensus participation.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "cometbft_consensus_late_votes{job=\"$job\"}",
     "legendFormat": "Vote Type: {{vote_type}}"
    }
   ]
  },
  { "title": "Token Distribution and Staking", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Nº Missing Validators ",
   "type": "stat",
   "description": "This metric shows the voting power (stake) that absent validators represent. A high power of absent validators can have a negative impact on the security and decentralization of the network, as it reduces the available consensus power.",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_missing_validators{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Power of Missing Validators ",
   "type": "stat",
   "description": "It measures the total voting power (stake) of validators that are absent in the network consensus process with the chain_id=“iliad-0”.This metric indicates the total amount of consensus power (in terms of stake) that has been lost due to the absence of certain validators. It is crucial to assess the impact that the absence of these validators has on the security and stability of the network, as more absent voting power can weaken the consensus of the blockchain.",
   "gridPos": { "h": 6, "w": 8, "x": 5, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_missing_validators_power{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Staking Withdrawal Depth",
   "type": "gauge",
   "description": "Indicates the depth of the withdrawal queue in an EVM-based staking system. A queue depth of zero means that all staking withdrawal transactions have been processed and there are no pending transactions.\nValue: number of pending staking withdrawal requests waiting to be processed.\n",
   "gridPos": { "h": 6, "w": 4, "x": 13, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "evmstaking_withdrawal_queue_depth{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Staking Queue Depth",
   "type": "stat",
   "description": "Indicates the depth of the reward queue in an EVM-based staking system. A queue depth of zero means that all staking reward transactions have been processed and there are no pending transactions.\nValue: number of pending staking reward requests waiting to be processed.\n",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "evmstaking_reward_queue_depth{job=\"$job\"}",
     "legendFormat": "Txs"
    }
   ]
  },
  { "title": "Validator data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Consensus Parameter Updates",
   "type": "stat",
   "description": "This metric counts how many times the application has updated the consensus parameters. These parameters define critical settings for the consensus process, such as block size, timeouts, and validator requirements. Monitoring this metric helps identify changes in the rules that govern the network's consensus mechanism. A high number of updates could indicate frequent tuning of network settings, which may affect how the network reaches consensus and how efficiently it operates.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_state_consensus_param_updates{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duplicate Block Part ",
   "type": "stat",
   "description": "This metric captures instances where a block part has been received multiple times, which could indicate potential inefficiencies or network issues. Monitoring this helps in identifying redundant data transmissions and optimizing network bandwidth.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_duplicate_block_part{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duplicate Vote",
   "type": "stat",
   "description": "This metric provides insight into how often duplicate votes are encountered during consensus. It could indicate potential misbehavior or inefficiencies in the voting process. Monitoring duplicate votes helps ensure the consensus protocol runs smoothly and efficiently",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_duplicate_vote{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Byzantine Validators Power ",
   "type": "timeseries",
   "description": "This metric indicates the total voting power of validators that have attempted to double-sign. It’s important for assessing the potential impact of byzantine activities on network consensus. A higher value could signal a significant threat to the network’s stability",
   "gridPos": { "h": 4, "w": 6, "x": 11, "y": 51 },
   "targets": [
    {
     "expr": "cometbft_consensus_byzantine_validators_power{job=\"$job\"}",
     "legendFormat": "total power of byzantine validators"
    }
   ]
  },
  {
   "title": "Byzantine Validators ",
   "type": "timeseries",
   "description": "Tracks the number of validators that attempted to double-sign. This metric helps identify validators that are engaging in byzantine behavior, such as attempting to create conflicting blocks. Monitoring this is crucial for maintaining the network’s integrity and security, as byzantine validators can potentially disrupt consensus.",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 51 },
   "targets": [
    {
     "expr": "cometbft_consensus_byzantine_validators{job=\"$job\"}",
     "legendFormat": "Nº validators that attempted to double-sign"
    }
   ]
  },
  { "title": "Transactions & gas", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Number of Transactions ",
   "type": "stat",
   "description": "Counts the transactions in the most recent block. Helps to understand the network activity and the load of transactions processed by the node.",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_num_txs{job=\"$job\"}",
     "legendFormat": "Txs"
    }
   ]
  },
  {
   "title": "Total Transactions ",
   "type": "timeseries",
   "description": "Shows the total number of transactions processed by the node. Indicates the total number of transactions processed in the chain by this node so far.",
   "gridPos": { "h": 6, "w": 6, "x": 5, "y": 56 },
   "targets": [
    {
     "expr": "cometbft_consensus_total_txs{job=\"$job\"}",
     "legendFormat": "Txs"
    }
   ]
  },
  {
   "title": "Successful Transactions",
   "type": "timeseries",
   "description": "Counts the total number of successfully executed transactions in the network. This metric provides insight into the overall reliability and performance of the blockchain, tracking how many transactions have been completed without errors.",
   "gridPos": { "h": 6, "w": 7, "x": 11, "y": 56 },
   "targets": [
    {
     "expr": "cosmos_tx_successful{job=\"$job\"}",
     "legendFormat": "Txs"
    }
   ]
  },
  {
   "title": "Transaction Count ",
   "type": "timeseries",
   "description": "Records the total number of transactions performed. Helps to measure overall network activity by counting all transactions processed.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 56 },
   "targets": [
    {
     "expr": "cosmos_tx_count{job=\"$job\"}",
     "legendFormat": "Txs"
    }
   ]
  },
  {
   "title": "Gas Used",
   "type": "timeseries",
   "description": "Indicates the amount of gas used in transactions. Reflects the gas consumed by recent transactions, which can show the efficiency of transactions.",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 62 },
   "targets": [
    {
     "expr": "cosmos_tx_gas_used{job=\"$job\"}",
     "legendFormat": "Gas used"
    }
   ]
  },
  {
   "title": "Gas Wanted",
   "type": "timeseries",
   "description": "Indicates the amount of gas requested in the transactions. Shows the gas that users estimated would be needed for their transactions.",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 62 },
   "targets": [
    {
     "expr": "cosmos_tx_gas_wanted{job=\"$job\"}",
     "legendFormat": "Gas requested"
    }
   ]
  },
  { "title": "Mempool & P2P", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "P2P Metrics ",
   "type": "barchart",
   "description": "Measures the number of bytes received for each message type. Monitors the amount of data received from other nodes for different types of messages, such as blocks or status responses.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 70 },
   "targets": [
    {
     "expr": "cometbft_p2p_message_receive_bytes_total{job=\"$job\"}",
     "legendFormat": "{{message_type}}"
    }
   ]
  },
  {
   "title": "P2P Message Send Bytes Total ",
   "type": "timeseries",
   "description": "This metric records the total volume of data, in bytes, that is being sent by the node for different message types over the P2P network. These message types are crucial for network operations, such as block responses, votes, consensus steps, and peer exchanges. Monitoring the bytes sent for each message type helps assess network bandwidth usage and detect potential bottlenecks or issues in message propagation. A high amount of data sent for messages like consensus_BlockPart or consensus_Vote reflects heavy network activity, especially during consensus processes. Tracking this helps ensure the node is not overwhelmed by sending too much data at once, which could degrade performance.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 78 },
   "targets": [
    {
     "expr": "cometbft_p2p_message_send_bytes_total{job=\"$job\"}",
     "legendFormat": "message_type: {{message_type}}"
    }
   ]
  },
  { "title": "System Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 } },
  {
   "title": "Runtime Free Count ",
   "type": "timeseries",
   "description": "Counts the number of times memory was freed in the system. Indicates how many memory free operations have been performed by the runtime since the start of the process, helping to understand the efficiency of memory usage.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
   "targets": [
    {
     "expr": "cosmos_runtime_free_count{job=\"$job\"}",
     "legendFormat": "memory free operations performed by the runtime"
    }
   ]
  },
  {
   "title": "GC Pause Time ",
   "type": "barchart",
   "description": "Measures how long the rubbish collector (GC) has paused execution. Allows to evaluate the impact of rubbish collection on system performance by showing how long it is paused to free memory.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 87 },
   "targets": [
    {
     "expr": "cosmos_runtime_gc_pause_ns{job=\"$job\"}",
     "legendFormat": "quantile: {{quantile}}"
    }
   ]
  },
  {
   "title": "Number of Goroutines ",
   "type": "timeseries",
   "description": "Indicates the number of goroutines running. Reflects the number of concurrent tasks active on the system, providing a view of concurrency.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 95 },
   "targets": [
    {
     "expr": "cosmos_runtime_num_goroutines{job=\"$job\"}",
     "legendFormat": "Nº goroutines in execution. "
    }
   ]
  },
  {
   "title": "System Bytes ",
   "type": "timeseries",
   "description": "Displays the total amount of memory allocated by the system. Reflects the total memory in use by runtime and other system resources.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 95 },
   "targets": [
    {
     "expr": "cosmos_runtime_sys_bytes{job=\"$job\"}",
     "legendFormat": "memory allocated by the system.  "
    }
   ]
  },
  {
   "title": "Process Memory in Use",
   "type": "stat",
   "description": "Measures the amount of memory allocated and still in use in the process. This metric indicates how many bytes of memory the process is currently using. It is essential for monitoring the node's memory usage, as a significant increase could affect its performance and stability. The metric helps to detect potential problems related to memory management, which can lead to optimisation of system resource usage.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cosmos_runtime_alloc_bytes{job=\"$job\"}",
     "legendFormat": "bytes"
    }
   ]
  }
 ]
}